name = "lol-stats"
main = "src/index.js"
compatibility_date = "2026-02-03"
compatibility_flags = ["nodejs_compat"]

[vars]
GITHUB_USER = "closur3"
GITHUB_REPO = "lol-stats-archive"
FANDOM_USER = "HsuX"
CRON_INTERVAL_MINUTES = "3"
SLOW_THRESHOLD_MINUTES = "60"
UPDATE_ROUNDS = "1"
MAX_SCHEDULE_DAYS = "8"

[[kv_namespaces]]
binding = "lol-stats-kv"
id = "caebca8919434b009d1b80fa89ff818f"

[observability]
[observability.logs]
enabled = true
invocation_logs = true

[triggers]
crons = ["*/3 * * * *"]

# 构建配置
[build]
command = "echo 'No build step needed for ES modules'"

[build.upload]
format = "modules"
