name = "lol-stats"
main = "src/index.js"
compatibility_date = "2026-02-03"
compatibility_flags = ["nodejs_compat"]

[vars]
GITHUB_USER = "closur3"
GITHUB_REPO = "lol-stats-archive"
FANDOM_USER = "HsuX"

[[kv_namespaces]]
binding = "lol-stats-kv"
id = "eac61be4fd134ab7a4282bf749791563"

[observability]
[observability.logs]
enabled = true
invocation_logs = true

[triggers]
crons = ["0 0 * * *", "*/2 8-15 * * wed,thu,fri,sat,sun"]

[dev]
ip = "0.0.0.0"
port = 8787
