name = "lol-stats"
main = "src/index.js"
compatibility_date = "2026-02-03"
compatibility_flags = ["nodejs_compat"]

[vars]
GITHUB_USER = "closur3"
GITHUB_REPO = "lol-stats-archive"
FANDOM_USER = "HsuX"
CRON_INTERVAL_MINUTES = "5"

[[kv_namespaces]]
binding = "LOL_KV"
id = "c96e310d082645b8a8fe254db1c3bc92"

[observability]
[observability.logs]
enabled = true
invocation_logs = true

[triggers]
crons = ["*/5 * * * *"]

# 构建配置
[build]
command = "echo 'No build step needed for ES modules'"

[build.upload]
format = "modules"